Bank.Web/Bank.Web/Models/Banking/ViewBanking.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bank.Web.Models.Banking
{
    public class ViewBanking
    {
        public string CurrentBalance { get; set; }
        public double? AmountToDeposit { get; set; }
        public double? AmountToWithdraw { get; set; }
    }
}

Bank.Web/Bank.Web/Models/ErrorViewModel.cs
using System;

namespace Bank.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bank.Web/Bank.Web/Controllers/BankingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Bank.Web.Models;
using Bank.Web.Models.Banking;
using Bank.Domain.Dal.Banking.Command;
using Bank.Common.ApiSettings;
using Bank.Domain.Model.Account;
using System.Net;

namespace Bank.Web.Controllers
{
    public class BankingController : Controller
    {
        #region Variables

        private const string ViewPrefix = "~/Views/Banking/";
        private const string ViewSuffix = ".cshtml";
        private IConfiguration _configuration;
        protected ClientApi _clientApi = null;

        #endregion Variables

        #region Constructor

        public BankingController(IConfiguration configuration)
        {
            _configuration = configuration;

            _clientApi = new ClientApi(configuration.GetConnectionString("Banking_API"), Guid.NewGuid().ToString()); //for now auto generate always a token but it shoudn't be this way
        }

        #endregion Constructor

        #region Get

        public async Task<IActionResult> Index()
        {
            ViewBanking model = new ViewBanking();

            string response = await _clientApi.CallApiGetString<string>("banking");

            model.CurrentBalance = response.Replace(@"""", string.Empty);

            return View(ViewPrefix + "Index" + ViewSuffix, model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        #endregion Get

        #region Post

        [HttpPost("deposit")]
        public async Task<IActionResult> Deposit(ViewBanking viewCommand)
        {
            DepositCommand command = new DepositCommand();
            command.Amount = viewCommand.AmountToDeposit.Value;

            string json = JsonConvert.SerializeObject(command);
            HttpContent content = new StringContent(json, Encoding.UTF8, "application/json");

            string response
                = await _clientApi.CallApiPostString<string>("banking/deposit", content);

            if (string.IsNullOrWhiteSpace(response) || (response.Contains("StatusCode")
                && int.Parse(JObject.Parse(response).SelectToken("StatusCode").ToString()) != (int)HttpStatusCode.OK))
                return BadRequest(JObject.Parse(response).SelectToken("Message").ToString());

            return Json(response.Replace(@"""", string.Empty));
        }

        [HttpPost("withdraw")]
        public async Task<IActionResult> Withdraw(ViewBanking viewCommand)
        {
            WithdrawCommand command = new WithdrawCommand();
            command.Amount = viewCommand.AmountToWithdraw.Value;

            string json = JsonConvert.SerializeObject(command);
            HttpContent content = new StringContent(json, Encoding.UTF8, "application/json");

            string response
                 = await _clientApi.CallApiPutString<string>("banking/withdraw", content);

            if (string.IsNullOrWhiteSpace(response) || (response.Contains("StatusCode")
                && int.Parse(JObject.Parse(response).SelectToken("StatusCode").ToString()) != (int)HttpStatusCode.OK))
                return BadRequest(JObject.Parse(response).SelectToken("Message").ToString());

            return Json(response.Replace(@"""", string.Empty));
        }


        #endregion Post
    }
}

Bank.Web/Bank.Web/Views/Banking/Index.cshtml
@using Bank.Web.Models.Banking
@model ViewBanking
@{
    ViewData["Title"] = "Banking Transaction";
}

@section Styles {
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/css/banking.scss")" />
}

@section Scripts
{
    <script type="text/javascript" src="@Url.Content("~/js/notify.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/js/banking.js")"></script>
}
<div id="divLoading" class="ajax-loading text-center" hidden>
    <p>
        Loading... Please wait...<img src="~/img/loader/ajax-loader.gif" />
    </p>
</div>

<div align="center" class="container-fluid" id="pnl-banking" data-deposit="@Url.Action("Deposit", "Banking")" data-withdraw="@Url.Action("Withdraw", "Banking")">
    <h1 class="display-4 text-center">Mini-Banking App</h1>
    <div class="">
        <div class="col-xs-9 col-md-4">
            <div class="card-body">
                <div class="card text-center">
                    <div class="row">
                        <div class="card-body property-card">
                            <label class="control-label col-sm-12">Current Balance: </label>
                            <div class="col-sm-12">
                                <div id="div-current-balance">
                                    @Model.CurrentBalance
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="">
        <partial name="/Views/Banking/_Deposit.cshtml" />
        <partial name="/Views/Banking/_Withdraw.cshtml" />
    </div>
</div>

Bank.Web/Bank.Web/Views/Banking/_Deposit.cshtml
<div class="col-xs-9 col-md-8">
    <div class="card-body">
        <div class="card">
            <div class="row">
                <div class="card-body property-card">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <div class="row row-no-gutters">
                                <div class="col-sm-6">
                                    <label class="control-label col-sm-12">Deposit amount: </label>
                                </div>
                                <div class="col-sm-6">
                                    <input type="number" class="form-control"  id="txt-deposit-amount" nkeypress="return IsNumberKey(event)" min="300" max="10000" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <button type="button" id="btn-deposit">Deposit</button>
        </div>
    </div>
</div>

Bank.Web/Bank.Web/Views/Banking/_Withdraw.cshtml
<div class="col-xs-9 col-md-8">
    <div class="card-body">
        <div class="card">
            <div class="row">
                <div class="card-body property-card">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <div class="row row-no-gutters">
                                <div class="col-sm-6">
                                    <label class="control-label col-sm-12">Withdrawal amount: </label>
                                </div>
                                <div class="col-sm-6">
                                    <input type="number" class="form-control" id="txt-withdraw-amount" nkeypress="return IsNumberKey(event)" min="300" max="10000" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <button type="button" id="btn-withdraw">Withdraw</button>
        </div>
    </div>
</div>

Bank.Web/Bank.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bank.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bank.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Npv" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Npv" asp-action="GetTransactionHistory"title="Go to History">Transaction History</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
            </script>
        </environment>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("Scripts", required: true)
    </footer>
</body>
</html>